### ISSUE TITLE
Improve the way new values match existing ones

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/FontClassificationTool#9]
Improve the way new values match existing ones from `font-metadata.csv`:
- [x] Normalize our float values to int values from 1 to 10, so they compare to original data. 
- [ ] With https://github.com/googlefonts/fontbakery/commit/75e7169b911c2b444ec375cf5a5170020cbd1e65 https://github.com/googlefonts/fontbakery/commit/67f2cc0573185ab3486a39c0c41d6d9d261a793f https://github.com/googlefonts/fontbakery/commit/864f111cdb5a2ea0ba1f1ee5a1a4f2d2da18fdd9 then the values are normalized within their own set, but making them match the original data needs more work. However, this may not be needed, as our data could be better than the original.

(originally reported at googlefonts/fontbakery#684)

**Comment by felipesanches** [comment]
@davelab6, What did you mean by "more work"?

At this point I'm leaning towards re-generating all the data from scratch.

**Comment by davelab6** [comment]
If you want to regenerate it all, that's fine; we can put it on a private sandbox of the directory and check that the results look right.

**Comment by felipesanches** [comment]
yeah... I am only reusing the italic angle values from the existing CSV, and all the rest is computed from scratch in my current implementation.

**Comment by felipesanches** [comment]
we're good here now.
